# Copyright 2026 Yunus Emre Cogurcu - Apache-2.0
"""IR → URScript translator: converts vendor-neutral Task IR to UR5e URScript programs."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from enfield_translators.urscript_utils import (
    format_float,
    joints_to_urscript,
    mm_s2_to_m_s2,
    mm_s_to_m_s,
    mm_to_m,
    pose_to_urscript,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Default kinematic parameters (UR5e conservative defaults)
# ---------------------------------------------------------------------------
_DEFAULT_ACCEL_M_S2 = 1.2  # m/s²  (URScript default for movel)
_DEFAULT_JOINT_ACCEL_RAD_S2 = 1.4  # rad/s²  (URScript default for movej)
_DEFAULT_JOINT_VEL_RAD_S = 1.05  # rad/s  (URScript default for movej)


class IRToURScriptTranslator:
    """Translate a Task IR dict into a URScript program string.

    The translator reads the vendor-neutral IR and emits syntactically
    correct URScript (.script) that can run on a UR5e controller or
    URSim simulator.

    Unit conversions applied automatically:
        - Position: mm → m
        - Speed: mm/s → m/s
        - Acceleration: mm/s² → m/s²
        - Orientation: quaternion → axis-angle
        - Joint angles: rad → rad (no change)
    """

    def __init__(self, *, indent: int = 2) -> None:
        self._indent = " " * indent

    # -------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------

    def translate(self, task: dict[str, Any]) -> str:
        """Translate a parsed Task IR dict to URScript.

        Args:
            task: Parsed JSON task dictionary.

        Returns:
            Complete URScript program as a string.
        """
        lines: list[str] = []

        meta = task.get("task", {})
        safety = task.get("safety_requirements", {})
        task_id = meta.get("id", "T000")
        task_name = meta.get("name", "unnamed")
        mode = meta.get("operating_mode", "collaborative")
        max_speed = safety.get("max_tcp_speed_mm_s", 250.0)

        # --- Header ---
        lines.append(f"# Task: {task_id} — {task_name}")
        lines.append("# Generated by ENFIELD IR→URScript Translator")
        lines.append(f"# Operating mode: {mode} | Max TCP speed: {mm_s_to_m_s(max_speed):.3f} m/s")
        lines.append(f"# Robot: {task.get('robot', {}).get('model', 'ur5e')}")
        lines.append("#")
        lines.append("# WARNING: This is auto-generated code for SIMULATION ONLY.")
        lines.append("# Do NOT deploy to a physical robot without safety review.")
        lines.append("")

        # --- Program function ---
        func_name = f"task_{task_id}"
        lines.append(f"def {func_name}():")

        # Emit each command
        for cmd in task.get("motion_sequence", []):
            cmd_lines = self._translate_command(cmd, task)
            for cl in cmd_lines:
                lines.append(f"{self._indent}{cl}")

        lines.append("end")
        lines.append("")

        # --- Entry point ---
        lines.append(f"# Entry point")
        lines.append(f"{func_name}()")
        lines.append("")

        return "\n".join(lines)

    def translate_file(self, json_path: str | Path) -> str:
        """Load a Task IR JSON file and translate to URScript.

        Args:
            json_path: Path to .json Task IR file.

        Returns:
            URScript program string.
        """
        path = Path(json_path)
        with open(path, "r") as f:
            task = json.load(f)
        return self.translate(task)

    def translate_to_file(
        self,
        json_path: str | Path,
        output_path: str | Path,
    ) -> Path:
        """Translate a Task IR file and write the URScript to disk.

        Args:
            json_path: Input .json path.
            output_path: Output .script path.

        Returns:
            Path to the written .script file.
        """
        script = self.translate_file(json_path)
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w") as f:
            f.write(script)
        logger.info("Wrote %s (%d lines)", out, script.count("\n"))
        return out

    def batch_translate(
        self,
        tasks_dir: str | Path,
        output_dir: str | Path,
        pattern: str = "T*.json",
    ) -> list[dict[str, str]]:
        """Translate all matching Task IR files in a directory.

        Args:
            tasks_dir: Directory with .json IR files.
            output_dir: Directory for .script outputs.
            pattern: Glob pattern for input files.

        Returns:
            List of manifest entries: [{task_id, input, output, lines}].
        """
        tasks_path = Path(tasks_dir)
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        manifest: list[dict[str, str]] = []

        for jf in sorted(tasks_path.glob(pattern)):
            try:
                with open(jf) as f:
                    task = json.load(f)
                task_id = task.get("task", {}).get("id", jf.stem)
                script = self.translate(task)

                out_file = out_path / f"{jf.stem}.script"
                with open(out_file, "w") as f:
                    f.write(script)

                entry = {
                    "task_id": task_id,
                    "input": str(jf.name),
                    "output": str(out_file.name),
                    "lines": script.count("\n"),
                }
                manifest.append(entry)
                logger.info("  → %s (%d lines)", out_file.name, entry["lines"])

            except Exception as exc:
                logger.error("  ✗ %s failed: %s", jf.name, exc)

        # Write manifest
        manifest_file = out_path / "manifest.json"
        with open(manifest_file, "w") as f:
            json.dump(manifest, f, indent=2)
        logger.info("Manifest: %s (%d files)", manifest_file, len(manifest))

        return manifest

    # -------------------------------------------------------------------
    # Command translators
    # -------------------------------------------------------------------

    def _translate_command(
        self, cmd: dict[str, Any], task: dict[str, Any]
    ) -> list[str]:
        """Dispatch a single IR command to its URScript equivalent."""
        cmd_type = cmd.get("type", "")
        label = cmd.get("label", "")
        seq = cmd.get("seq", 0)

        lines: list[str] = []
        if label:
            lines.append(f"# [{seq}] {label}")

        handler = {
            "move_linear": self._cmd_move_linear,
            "move_joint": self._cmd_move_joint,
            "move_circular": self._cmd_move_circular,
            "set_tool": self._cmd_set_tool,
            "set_digital_output": self._cmd_set_digital_output,
            "wait": self._cmd_wait,
            "estop_check": self._cmd_estop_check,
            "comment": self._cmd_comment,
        }.get(cmd_type)

        if handler is None:
            lines.append(f"# WARNING: Unknown command type '{cmd_type}' (seq={seq})")
        else:
            lines.extend(handler(cmd, task))

        lines.append("")  # blank line between commands
        return lines

    def _cmd_move_linear(
        self, cmd: dict[str, Any], task: dict[str, Any]
    ) -> list[str]:
        """move_linear → movel(pose, a, v, t, r)"""
        tp = cmd.get("target_pose", {})
        pos = tp.get("position", {})
        orient = tp.get("orientation")

        pose_str = pose_to_urscript(pos, orient)

        v = mm_s_to_m_s(cmd.get("speed_mm_s", 250.0))
        a = mm_s2_to_m_s2(cmd.get("accel_mm_s2", 1200.0))
        r = mm_to_m(cmd.get("blend_radius_mm", 0.0))

        parts = [f"a={format_float(a)}", f"v={format_float(v)}"]
        if r > 0:
            parts.append(f"r={format_float(r)}")

        return [f"movel({pose_str}, {', '.join(parts)})"]

    def _cmd_move_joint(
        self, cmd: dict[str, Any], task: dict[str, Any]
    ) -> list[str]:
        """move_joint → movej(q, a, v)"""
        tj = cmd.get("target_joints", {})
        values = tj.get("values", [0.0] * 6)
        joints_str = joints_to_urscript(values)

        # URScript movej uses rad/s for velocity.
        # IR speed_mm_s is TCP speed — approximate conversion:
        # Use a conservative joint velocity based on TCP speed.
        tcp_speed = cmd.get("speed_mm_s", 200.0)
        # Heuristic: joint_vel ≈ tcp_speed_m_s / avg_link_length(~0.4m)
        joint_vel = min(mm_s_to_m_s(tcp_speed) / 0.4, _DEFAULT_JOINT_VEL_RAD_S)

        return [f"movej({joints_str}, a={format_float(_DEFAULT_JOINT_ACCEL_RAD_S2)}, v={format_float(joint_vel)})"]

    def _cmd_move_circular(
        self, cmd: dict[str, Any], task: dict[str, Any]
    ) -> list[str]:
        """move_circular → movec(pose_via, pose_to, a, v, r)"""
        via = cmd.get("via_pose", {})
        tp = cmd.get("target_pose", {})

        via_str = pose_to_urscript(
            via.get("position", {"x": 0, "y": 0, "z": 0}),
            via.get("orientation"),
        )
        target_str = pose_to_urscript(
            tp.get("position", {"x": 0, "y": 0, "z": 0}),
            tp.get("orientation"),
        )

        v = mm_s_to_m_s(cmd.get("speed_mm_s", 100.0))
        a = mm_s2_to_m_s2(cmd.get("accel_mm_s2", 600.0))
        r = mm_to_m(cmd.get("blend_radius_mm", 0.0))

        parts = [f"a={format_float(a)}", f"v={format_float(v)}"]
        if r > 0:
            parts.append(f"r={format_float(r)}")

        return [f"movec({via_str}, {target_str}, {', '.join(parts)})"]

    def _cmd_set_tool(
        self, cmd: dict[str, Any], task: dict[str, Any]
    ) -> list[str]:
        """set_tool → set_digital_out / set_analog_out depending on tool type."""
        params = cmd.get("tool_parameters", {})
        tool_type = task.get("tool", {}).get("type", "gripper")
        lines: list[str] = []

        if tool_type == "gripper":
            state = params.get("state", params.get("grip_state", 0.0))
            force = params.get("grip_force_n", params.get("grip_force_N", 0.0))
            if state > 0.5:
                lines.append(f"# Gripper CLOSE (force={force:.0f} N)")
                lines.append("set_digital_out(0, True)")
            else:
                lines.append("# Gripper OPEN")
                lines.append("set_digital_out(0, False)")

        elif tool_type == "welder":
            arc_on = params.get("arc_on", 0.0)
            current = params.get("welding_current_A", 0.0)
            wire = params.get("wire_feed_m_min", 0.0)
            if arc_on > 0.5:
                lines.append(f"# Welding arc ON (I={current:.0f}A, wire={wire:.1f}m/min)")
                lines.append("set_digital_out(0, True)   # arc enable")
                lines.append(f"set_analog_out(0, {current / 300.0:.3f})  # current (normalized)")
                lines.append(f"set_analog_out(1, {wire / 15.0:.3f})  # wire feed (normalized)")
            else:
                lines.append("# Welding arc OFF")
                lines.append("set_digital_out(0, False)")
                lines.append("set_analog_out(0, 0.0)")
                lines.append("set_analog_out(1, 0.0)")

        else:
            # Generic: emit parameters as comments + digital out
            lines.append(f"# set_tool ({tool_type}): {params}")
            if params:
                lines.append("set_digital_out(0, True)")

        return lines

    def _cmd_set_digital_output(
        self, cmd: dict[str, Any], task: dict[str, Any]
    ) -> list[str]:
        """set_digital_output → set_digital_out(port, value)"""
        io = cmd.get("io_signal", {})
        port = io.get("port", 0)
        value = io.get("value", False)
        return [f"set_digital_out({port}, {value})"]

    def _cmd_wait(
        self, cmd: dict[str, Any], task: dict[str, Any]
    ) -> list[str]:
        """wait → sleep(duration)"""
        duration = cmd.get("duration_s", 1.0)
        return [f"sleep({format_float(duration)})"]

    def _cmd_estop_check(
        self, cmd: dict[str, Any], task: dict[str, Any]
    ) -> list[str]:
        """estop_check → safety check comment + popup guard.

        On a real UR controller, E-Stop is handled by the safety system
        hardware and cannot be bypassed by URScript. We emit a
        protective check using ``get_digital_in`` as a software guard.
        """
        return [
            "# E-Stop safety check (hardware-enforced on UR controller)",
            "if (get_digital_in(0) == True):",
            "  popup(\"E-Stop active — aborting program.\", error=True)",
            "  halt",
            "end",
        ]

    def _cmd_comment(
        self, cmd: dict[str, Any], task: dict[str, Any]
    ) -> list[str]:
        """comment → # comment text"""
        text = cmd.get("comment_text", cmd.get("label", ""))
        return [f"# {text}"]


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """CLI: translate Task IR files to URScript."""
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    parser = argparse.ArgumentParser(
        description="Translate Task IR JSON files to URScript (.script)."
    )
    parser.add_argument(
        "--tasks-dir",
        type=str,
        default="ir/tasks",
        help="Directory containing Task IR .json files.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="generated/urscript",
        help="Output directory for .script files.",
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="T*.json",
        help="Glob pattern for input files.",
    )

    args = parser.parse_args()
    translator = IRToURScriptTranslator()
    manifest = translator.batch_translate(
        tasks_dir=args.tasks_dir,
        output_dir=args.output_dir,
        pattern=args.pattern,
    )
    print(f"\nDone: {len(manifest)} scripts generated.")


if __name__ == "__main__":
    main()
