#!/usr/bin/env python3
# Copyright 2026 Yunus Emre Cogurcu - Apache-2.0
"""Per-strategy x per-model table for the adversarial experiment (E2).

Revision item R2-5 (IEEE Access Access-2026-32028): the adversarial arm
(315 generations) appeared in the manuscript only as prose. This script
builds the full breakdown from the shipped result CSVs and writes it as
CSV, Markdown and a booktabs LaTeX table.

Two denominators are reported side by side, because the manuscript mixed
them (R2-3b): "all" counts invalid / errored outputs as zero violations
(135-row basis, gives the 6.38 baseline mean), "gate" restricts to outputs
that passed the URScript validity gate (status == success; 83-row basis,
gives the 10.37 baseline mean).

Usage:
    python3 scripts/review/adversarial_table.py \
        --e1 results/E1_full/e1_results.csv \
        --e2 results/E2_full/e2_results.csv \
        --out-dir paper/tables
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

MODEL_LABEL = {
    "qwen2.5-coder:32b": "Qwen2.5-Coder-32B",
    "deepseek-coder-v2:16b": "DeepSeek-Coder-V2-16B",
    "codellama:34b": "CodeLlama-34B",
}
MODEL_ORDER = list(MODEL_LABEL)
STRATEGY_LABEL = {
    "baseline": "Baseline (E1, 3 reps)",
    "A8.1": "A8.1 Direct override",
    "A8.2": "A8.2 Role-playing",
    "A8.3": "A8.3 Context overflow",
    "A8.4": "A8.4 Incremental",
    "A8.5": "A8.5 Authority claim",
    "A8.6": "A8.6 Performance framing",
    "A8.7": "A8.7 Obfuscation",
}


def _summarise(df: pd.DataFrame) -> dict[str, float]:
    gate = df[df["status"] == "success"]
    n = len(df)
    return {
        "n": n,
        "gate_n": len(gate),
        "gate_rate": len(gate) / n if n else float("nan"),
        "viol_rate_all": (df["total_violations"] > 0).mean() if n else float("nan"),
        "viol_rate_gate": (gate["total_violations"] > 0).mean() if len(gate) else float("nan"),
        "mean_viol_all": df["total_violations"].mean() if n else float("nan"),
        "mean_viol_gate": gate["total_violations"].mean() if len(gate) else float("nan"),
        "sev_max_gate": gate["severity_max"].mean() if len(gate) else float("nan"),
    }


def build(e1: pd.DataFrame, e2: pd.DataFrame) -> pd.DataFrame:
    base = e1[e1["condition"] == "baseline"].copy()
    base["strategy"] = "baseline"
    adv = e2.copy()
    adv["strategy"] = adv["adversarial_type"]
    frames = pd.concat([base, adv], ignore_index=True)

    rows = []
    for strat in STRATEGY_LABEL:
        sub = frames[frames["strategy"] == strat]
        if sub.empty:
            continue
        for model in MODEL_ORDER + ["pooled"]:
            part = sub if model == "pooled" else sub[sub["model"] == model]
            rec = {"strategy": strat, "model": model}
            rec.update(_summarise(part))
            rows.append(rec)
    return pd.DataFrame(rows)


def to_markdown(t: pd.DataFrame) -> str:
    out = ["| Strategy | Model | n | Gate-pass | Viol. rate (all) | Viol. rate (gate) | Mean viol. (all) | Mean viol. (gate) | Sev. max (gate) |",
           "|---|---|---:|---:|---:|---:|---:|---:|---:|"]
    for _, r in t.iterrows():
        out.append(
            f"| {STRATEGY_LABEL[r.strategy]} | {MODEL_LABEL.get(r.model, r.model)} | {int(r.n)} | "
            f"{int(r.gate_n)} ({100*r.gate_rate:.0f}%) | {100*r.viol_rate_all:.1f}% | "
            f"{100*r.viol_rate_gate:.1f}% | {r.mean_viol_all:.2f} | {r.mean_viol_gate:.2f} | {r.sev_max_gate:.2f} |"
        )
    return "\n".join(out) + "\n"


def to_latex(t: pd.DataFrame) -> str:
    """Compact booktabs table: one block per strategy, one row per model + pooled."""
    lines = [
        "% Generated by scripts/review/adversarial_table.py -- do not edit by hand",
        "\\begin{table*}[t]",
        "\\caption{Adversarial experiment (E2) by prompt-injection strategy and model, with the",
        "matched baseline from E1 for reference. $n$ is the number of generations; gate-pass is",
        "the count (and share) that passed the URScript validity gate. Violation rates and mean",
        "violation counts are given on two bases: \\emph{all} scores invalid or errored outputs",
        "as zero violations, \\emph{gate} restricts to gate-passing outputs. Severity is the mean",
        "of the per-generation maximum rule severity on the gate-passing basis. E2 uses one",
        "repetition per cell (45 cells per strategy); the baseline row pools three repetitions.}",
        "\\label{tab:adversarial}",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{@{}llrrrrrrr@{}}",
        "\\toprule",
        "Strategy & Model & $n$ & Gate-pass & \\multicolumn{2}{c}{Violation rate} & \\multicolumn{2}{c}{Mean violations} & Sev. \\\\",
        "\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}",
        " & & & & all & gate & all & gate & gate \\\\",
        "\\midrule",
    ]
    first = True
    for strat in STRATEGY_LABEL:
        block = t[t["strategy"] == strat]
        if block.empty:
            continue
        if not first:
            lines.append("\\addlinespace")
        first = False
        for i, (_, r) in enumerate(block.iterrows()):
            label = STRATEGY_LABEL[strat].replace("&", "\\&") if i == 0 else ""
            model = MODEL_LABEL.get(r.model, "Pooled")
            if r.model == "pooled":
                model = "\\textit{Pooled}"
            lines.append(
                f"{label} & {model} & {int(r.n)} & {int(r.gate_n)} ({100*r.gate_rate:.0f}\\%) & "
                f"{100*r.viol_rate_all:.1f} & {100*r.viol_rate_gate:.1f} & "
                f"{r.mean_viol_all:.2f} & {r.mean_viol_gate:.2f} & {r.sev_max_gate:.2f} \\\\"
            )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--e1", type=Path, default=Path("results/E1_full/e1_results.csv"))
    ap.add_argument("--e2", type=Path, default=Path("results/E2_full/e2_results.csv"))
    ap.add_argument("--out-dir", type=Path, default=Path("paper/tables"))
    args = ap.parse_args()

    e1 = pd.read_csv(args.e1)
    e2 = pd.read_csv(args.e2)
    table = build(e1, e2)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    table.to_csv(args.out_dir / "adversarial_table.csv", index=False)
    (args.out_dir / "adversarial_table.md").write_text(to_markdown(table))
    (args.out_dir / "adversarial_table.tex").write_text(to_latex(table))

    pooled = table[table["model"] == "pooled"].set_index("strategy")
    b = pooled.loc["baseline"]
    print(f"Baseline pooled: mean viol all={b.mean_viol_all:.2f} gate={b.mean_viol_gate:.2f} "
          f"(n={int(b.n)}, gate {int(b.gate_n)})")
    for s in pooled.index:
        if s == "baseline":
            continue
        r = pooled.loc[s]
        print(f"{s}: n={int(r.n)} gate={int(r.gate_n)} mean all={r.mean_viol_all:.2f} "
              f"(d={r.mean_viol_all-b.mean_viol_all:+.2f}) gate={r.mean_viol_gate:.2f} "
              f"(d={r.mean_viol_gate-b.mean_viol_gate:+.2f}) sev={r.sev_max_gate:.2f}")
    print(f"Wrote {args.out_dir}/adversarial_table.{{csv,md,tex}}")


if __name__ == "__main__":
    main()
