#!/usr/bin/env python3
# Copyright 2026 Yunus Emre Cogurcu - Apache-2.0
"""Compact complexity-stratified table (revision item R2-M5).

Condenses the output of scripts/complexity_correlation_analysis.py
(per_scenario_joined.csv) into one table: per experiment and condition,
the pooled violation count and binary rate by complexity tertile, and the
per-model Spearman rho between task complexity score and violation count
with its p-value. The preregistered expectation was a positive association;
the table reports it whether or not it is null.

Usage:
    python3 scripts/review/complexity_table.py \
        --joined paper/tables/complexity/per_scenario_joined.csv \
        --spearman paper/tables/complexity/spearman_summary.csv \
        --out-dir paper/tables
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

TERTILES = ["T_low", "T_med", "T_high"]
TLABEL = {"T_low": "Low", "T_med": "Medium", "T_high": "High"}
MODEL_SHORT = {"Qwen2.5-Coder-32B": "Qwen", "DeepSeek-Coder-V2-16B": "DeepSeek", "CodeLlama-34B": "CodeLlama"}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--joined", type=Path, default=Path("paper/tables/complexity/per_scenario_joined.csv"))
    ap.add_argument("--spearman", type=Path, default=Path("paper/tables/complexity/spearman_summary.csv"))
    ap.add_argument("--out-dir", type=Path, default=Path("paper/tables"))
    args = ap.parse_args()

    j = pd.read_csv(args.joined)
    s = pd.read_csv(args.spearman)
    value_col = "outcome_value" if "outcome_value" in j.columns else [c for c in j.columns if "value" in c][0]

    rows = []
    for (exp, cond), g in j.groupby(["experiment", "condition"]):
        if exp == "E2":
            continue  # seven strategies; reported in the adversarial table instead
        rec = {"experiment": exp, "condition": cond}
        for metric in ("cvr", "count"):
            gm = g[g.outcome_metric == metric]
            for t in TERTILES:
                gt = gm[gm.tertile == t]
                rec[f"{metric}_{t}"] = gt[value_col].mean() if len(gt) else float("nan")
                rec[f"n_{t}"] = gt.task_id.nunique() if len(gt) else 0
        sp = s[(s.experiment == exp) & (s.condition == cond) & (s.outcome_metric == "count")]
        rec["rho"] = "; ".join(
            f"{MODEL_SHORT.get(r.model, r.model)} {r.spearman_rho:+.2f} ($p$={r.p_value:.2f}, $n$={int(r.n_tasks)})"
            for _, r in sp.sort_values("model").iterrows())
        rows.append(rec)
    t = pd.DataFrame(rows)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    t.to_csv(args.out_dir / "complexity_table.csv", index=False)

    lines = [
        "% Generated by scripts/review/complexity_table.py -- do not edit by hand",
        "\\begin{table*}[t]",
        "\\caption{Complexity-stratified outcomes (preregistered non-confirmatory analysis).",
        "Tasks are split into tertiles of the outcome-blind complexity score",
        "(\\ref{sec:complexity}). Cells give the pooled gate-passing binary violation rate",
        "and mean violation count per tertile, with the number of tasks contributing, and the",
        "per-model Spearman correlation between complexity score and violation count over",
        "tasks with at least one gate-passing output. E3 uses the final retry of each cell.",
        "No correction for multiplicity is applied; with fifteen tasks and a saturated",
        "binary outcome the analysis is descriptive.}",
        "\\label{tab:complexity}",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{@{}llrrrrrrl@{}}",
        "\\toprule",
        "Exp. & Condition & \\multicolumn{3}{c}{Violation rate (\\%)} & \\multicolumn{3}{c}{Mean violations} & Spearman $\\rho$ (count) \\\\",
        "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}",
        " & & Low & Med. & High & Low & Med. & High & \\\\",
        "\\midrule",
    ]
    for _, r in t.iterrows():
        cond = {"baseline": "Baseline", "safety": "Safety-prompted"}.get(r.condition, r.condition)
        cv = " & ".join(f"{100*r[f'cvr_{x}']:.0f}" for x in TERTILES)
        cn = " & ".join(f"{r[f'count_{x}']:.1f}" for x in TERTILES)
        lines.append(f"{r.experiment} & {cond} & {cv} & {cn} & {r.rho} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    (args.out_dir / "complexity_table.tex").write_text("\n".join(lines))
    pd.set_option("display.width", 250)
    print(t.to_string(index=False))


if __name__ == "__main__":
    main()
