#!/usr/bin/env python3
# Copyright 2026 Yunus Emre Cogurcu - Apache-2.0
"""Non-LLM comparator for the rule checker (revision item R2-1).

Scores URScript programs that were NOT produced by a language model with
the same rule checker used on the generated code, so that the generated-code
violation rate can be read against a reference point:

  translator          the deterministic IR->URScript translator output for the
                      fifteen baseline tasks (minimal literal rendering)
  translator+preamble same, with set_tcp()/set_payload() emitted before the
                      first motion (what the safety-prompted condition asks for)
  vendor              optional: vendor or community example programs placed in
                      --vendor-dir (*.script / *.urscript / *.txt), scored as-is
  llm-baseline        for reference, the gate-passing E1 baseline generations

Every set is scored twice:
  preregistered  the rule set as registered and used in the manuscript
  corrected-SM5  identical, except SM-5 is replaced by scripts/sm5_corrected.py
                 (movej v treated as rad/s; per-task TCP cap from the IR)

Outputs a per-program CSV, a per-rule firing summary (CSV + LaTeX) and a
Markdown summary.

Usage:
    python3 scripts/review/comparator_urscript.py --out-dir paper/tables \
        [--vendor-dir data/vendor_urscript] [--e1-code results/E1_full/code]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "enfield_watchdog_static"))
sys.path.insert(0, str(REPO / "enfield_tasks"))
sys.path.insert(0, str(REPO / "enfield_translators"))
sys.path.insert(0, str(REPO / "scripts"))
sys.path.insert(0, str(REPO / "enfield_llm"))

from enfield_watchdog_static import StaticWatchdog  # noqa: E402
from enfield_translators.urscript_translator import IRToURScriptTranslator  # noqa: E402
from sm5_corrected import check_sm5_corrected  # noqa: E402
from enfield_llm.code_parser import URSCRIPT_CALL_PATTERN  # noqa: E402

RULES = ["SM-1", "SM-2", "SM-3", "SM-4", "SM-5", "SM-6", "SM-7"]
TASKS_DIR = REPO / "enfield_tasks" / "ir" / "tasks"


def load_task_caps() -> dict[str, float]:
    caps = {}
    for f in TASKS_DIR.glob("T*.json"):
        t = json.loads(f.read_text())
        tid = t.get("task", {}).get("id", f.stem[:4])
        caps[tid] = float(t.get("safety_requirements", {}).get("max_tcp_speed_mm_s", 250.0)) / 1000.0
    return caps


def score(code: str, tcp_cap: float | None, wd: StaticWatchdog) -> dict:
    report = wd.analyze_code(code)
    pre = {}
    for v in report.violations:
        pre[v.detection_mechanism] = pre.get(v.detection_mechanism, 0) + 1
    corr = {k: n for k, n in pre.items() if k != "SM-5"}
    sm5c = check_sm5_corrected(code, tcp_cap=tcp_cap)
    if sm5c:
        corr["SM-5"] = len(sm5c)
    rec = {"gate": int(bool(URSCRIPT_CALL_PATTERN.search(code)))}
    for r in RULES:
        rec[f"pre_{r}"] = pre.get(r, 0)
        rec[f"corr_{r}"] = corr.get(r, 0)
    rec["pre_total"] = sum(pre.values())
    rec["corr_total"] = sum(corr.values())
    rec["pre_flagged"] = int(rec["pre_total"] > 0)
    rec["corr_flagged"] = int(rec["corr_total"] > 0)
    return rec


def translator_programs(preamble: bool) -> list[tuple[str, str, str]]:
    tr = IRToURScriptTranslator(safety_preamble=preamble)
    out = []
    for f in sorted(TASKS_DIR.glob("T*.json")):
        out.append((f.stem[:4], f.stem, tr.translate_file(f)))
    return out


def dir_programs(d: Path, task_from_name: bool) -> list[tuple[str, str, str]]:
    out = []
    for f in sorted(p for p in d.iterdir() if p.suffix in {".script", ".urscript", ".txt"}):
        m = re.match(r"(T\d{3})", f.name) if task_from_name else None
        out.append((m.group(1) if m else "", f.name, f.read_text(errors="replace")))
    return out


def summarise(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for name, g in df.groupby("set", sort=False):
        for basis in ("pre", "corr"):
            rec = {"set": name, "basis": basis, "n": len(g),
                   "gate": int(g["gate"].sum()),
                   "flagged": int(g[f"{basis}_flagged"].sum()),
                   "mean_total": g[f"{basis}_total"].mean()}
            for r in RULES:
                rec[r] = int((g[f"{basis}_{r}"] > 0).sum())
            rows.append(rec)
    return pd.DataFrame(rows)


def to_latex(summ: pd.DataFrame) -> str:
    lines = [
        "% Generated by scripts/review/comparator_urscript.py -- do not edit by hand",
        "\\begin{table*}[t]",
        "\\caption{Non-LLM comparator. Programs that were not produced by a language model,",
        "scored with the same rule checker as the generated code. Columns SM-1 to SM-7 give the",
        "number of programs on which each check fires; gate is the number that pass the URScript",
        "validity gate; flagged is the number with at least one",
        "firing; mean is the mean number of firings per program. \\emph{Preregistered} is the rule",
        "set used for every confirmatory result; \\emph{corrected SM-5} replaces only the",
        "hardcoded-value check with a version that reads \\texttt{movej} velocities as joint",
        "speeds and applies the task's own TCP cap. The translator is the deterministic",
        "IR-to-URScript renderer of \\ref{sec:task-ir}; the LLM row is the gate-passing baseline",
        "generations of E1 for reference.}",
        "\\label{tab:comparator}",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{@{}llrrrrrrrrrrr@{}}",
        "\\toprule",
        "Program set & Rule set & $n$ & Gate & Flagged & Mean & SM-1 & SM-2 & SM-3 & SM-4 & SM-5 & SM-6 & SM-7 \\\\",
        "\\midrule",
    ]
    prev = None
    for _, r in summ.iterrows():
        if prev is not None and r["set"] != prev:
            lines.append("\\addlinespace")
        prev = r["set"]
        basis = "Preregistered" if r.basis == "pre" else "Corrected SM-5"
        cells = " & ".join(str(int(r[k])) for k in RULES)
        lines.append(f"{r['set']} & {basis} & {int(r.n)} & {int(r.gate)} & {int(r.flagged)} & {r.mean_total:.1f} & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--vendor-dir", type=Path, default=None)
    ap.add_argument("--e1-code", type=Path, default=REPO / "results" / "E1_full" / "code")
    ap.add_argument("--out-dir", type=Path, default=REPO / "paper" / "tables")
    args = ap.parse_args()

    caps = load_task_caps()
    wd = StaticWatchdog()
    rows = []

    sets: list[tuple[str, list[tuple[str, str, str]]]] = [
        ("Translator", translator_programs(False)),
        ("Translator + preamble", translator_programs(True)),
    ]
    if args.vendor_dir and args.vendor_dir.is_dir():
        sets.append(("Vendor / community examples", dir_programs(args.vendor_dir, task_from_name=False)))
    if args.e1_code.is_dir():
        llm = [(t, n, c) for t, n, c in dir_programs(args.e1_code, task_from_name=True)
               if "_baseline_" in n and ".invalid" not in n and n.endswith(".urscript")]
        sets.append(("LLM baseline (E1, gate-passing)", llm))

    for set_name, programs in sets:
        for tid, name, code in programs:
            rec = {"set": set_name, "task_id": tid, "program": name}
            rec.update(score(code, caps.get(tid), wd))
            rows.append(rec)

    df = pd.DataFrame(rows)
    summ = summarise(df)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(args.out_dir / "comparator_programs.csv", index=False)
    summ.to_csv(args.out_dir / "comparator_summary.csv", index=False)
    (args.out_dir / "comparator_summary.tex").write_text(to_latex(summ))

    pd.set_option("display.width", 200)
    print(summ.to_string(index=False))
    print(f"Wrote {args.out_dir}/comparator_{{programs,summary}}.csv and comparator_summary.tex")


if __name__ == "__main__":
    main()
