#!/usr/bin/env python3
# Copyright 2026 Yunus Emre Cogurcu - Apache-2.0
"""Precision audit v2: per-rule precision per rater, and inter-rater agreement.

Reads the two filled rater sheets produced by precision_audit_sample.py
(label column in {TP, FP, UNSURE}) and, optionally, an adjudicated sheet.
Reports per rule: n, TP per rater, precision with Clopper-Pearson 95% CI,
percent agreement and Cohen's kappa (TP vs FP; UNSURE excluded pairwise),
plus pooled kappa. Writes CSV and a booktabs LaTeX table.

Usage:
    python3 scripts/review/precision_audit_analyze.py \
        --a docs/review/audit_v2/sheet_rater_A.csv \
        --b docs/review/audit_v2/sheet_rater_B.csv \
        [--adjudicated docs/review/audit_v2/sheet_adjudicated.csv] \
        --out-dir paper/tables
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
from scipy.stats import beta

RULES = ["SM-1", "SM-2", "SM-3", "SM-4", "SM-5", "SM-6", "SM-7"]
RULE_LABEL = {
    "SM-1": "Input-validation proxy (CWE-20)",
    "SM-2": "Error-handling proxy (CWE-252)",
    "SM-3": "Protection mechanism (CWE-693)",
    "SM-4": "Unusual conditions (CWE-754)",
    "SM-5": "Hardcoded value (CWE-798)",
    "SM-6": "Safety preamble",
    "SM-7": "Prompt-injection marker",
}


def clopper_pearson(k: int, n: int, alpha: float = 0.05) -> tuple[float, float]:
    if n == 0:
        return float("nan"), float("nan")
    lo = 0.0 if k == 0 else beta.ppf(alpha / 2, k, n - k + 1)
    hi = 1.0 if k == n else beta.ppf(1 - alpha / 2, k + 1, n - k)
    return lo, hi


def kappa(a: pd.Series, b: pd.Series) -> tuple[float, float, int]:
    m = a.isin(["TP", "FP"]) & b.isin(["TP", "FP"])
    a, b = a[m], b[m]
    n = len(a)
    if n == 0:
        return float("nan"), float("nan"), 0
    po = (a == b).mean()
    pe = sum((a == c).mean() * (b == c).mean() for c in ["TP", "FP"])
    k = (po - pe) / (1 - pe) if pe < 1 else 1.0
    return po, k, n


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--a", type=Path, default=None, help="rater A sheet (author); optional until returned")
    ap.add_argument("--b", type=Path, required=True, help="rater B sheet (independent, non-author)")
    ap.add_argument("--adjudicated", type=Path, default=None)
    ap.add_argument("--out-dir", type=Path, default=Path("paper/tables"))
    args = ap.parse_args()

    b = pd.read_csv(args.b).set_index("item_id")
    b["label"] = b["label"].astype(str).str.strip().str.upper()
    single = args.a is None or not args.a.is_file()
    if single:
        a = b.copy()  # placeholder so the per-rule loop runs; A columns are suppressed below
    else:
        a = pd.read_csv(args.a).set_index("item_id")
        a["label"] = a["label"].astype(str).str.strip().str.upper()
    adj = None
    if args.adjudicated and args.adjudicated.is_file():
        adj = pd.read_csv(args.adjudicated).set_index("item_id")
        adj["label"] = adj["label"].astype(str).str.strip().str.upper()

    rows = []
    for rule in RULES + ["pooled"]:
        idx = a.index if rule == "pooled" else a.index[a["rule"] == rule]
        if len(idx) == 0:
            continue
        la, lb = a.loc[idx, "label"], b.loc[idx, "label"]
        rec = {"rule": rule, "n": len(idx)}
        for name, lab in (("A", la), ("B", lb)):
            n_dec = int(lab.isin(["TP", "FP"]).sum())
            tp = int((lab == "TP").sum())
            lo, hi = clopper_pearson(tp, n_dec)
            rec[f"tp_{name}"] = tp
            rec[f"n_{name}"] = n_dec
            rec[f"prec_{name}"] = tp / n_dec if n_dec else float("nan")
            rec[f"ci_{name}"] = f"[{100*lo:.1f}, {100*hi:.1f}]" if n_dec else "n/a"
        po, k, n_pairs = kappa(la, lb)
        rec.update({"agreement": po, "kappa": k, "n_pairs": n_pairs})
        if adj is not None:
            lj = adj.loc[idx, "label"]
            n_dec = int(lj.isin(["TP", "FP"]).sum())
            tp = int((lj == "TP").sum())
            lo, hi = clopper_pearson(tp, n_dec)
            rec.update({"tp_adj": tp, "n_adj": n_dec, "prec_adj": tp / n_dec if n_dec else float("nan"),
                        "ci_adj": f"[{100*lo:.1f}, {100*hi:.1f}]" if n_dec else "n/a"})
        rows.append(rec)
    t = pd.DataFrame(rows)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    t.to_csv(args.out_dir / "precision_audit_v2.csv", index=False)

    if single:
        lines = [
            "% Generated by scripts/review/precision_audit_analyze.py -- do not edit by hand",
            "\\begin{table}[t]",
            "\\caption{Precision audit v2 of the rule checker on gate-passing generated code",
            "(E1 and E2): 100 firings, 20 per firing rule, drawn with a fixed seed and labelled by",
            "an independent rater who is not an author and had not seen the manuscript, the rule",
            "code or the earlier audit. Precision is the share of audited firings judged genuine,",
            "with Clopper-Pearson 95\\% intervals. The two checks that never fire (SM-3, SM-7) are",
            "not represented.}",
            "\\label{tab:precision2}",
            "\\centering",
            "\\footnotesize",
            "\\begin{tabular}{@{}lrrl@{}}",
            "\\toprule",
            "Check & $n$ & TP & Precision, 95\\% CI \\\\",
            "\\midrule",
        ]
        for _, r in t.iterrows():
            label = RULE_LABEL.get(r.rule, "\\textit{Pooled}")
            if r.rule == "pooled":
                lines.append("\\midrule")
            lines.append(f"{label} & {int(r.n_B)} & {int(r.tp_B)} & {100*r.prec_B:.1f} {r.ci_B} \\\\")
        lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
        (args.out_dir / "precision_audit_v2.tex").write_text("\n".join(lines))
        pd.set_option("display.width", 200)
        print(t[["rule", "n", "tp_B", "n_B", "prec_B", "ci_B"]].to_string(index=False))
        return

    lines = [
        "% Generated by scripts/review/precision_audit_analyze.py -- do not edit by hand",
        "\\begin{table}[t]",
        "\\caption{Precision audit v2 of the rule checker on gate-passing generated code",
        "(E1 and E2), with two independent raters blind to each other's labels. Precision is",
        "the share of audited firings judged genuine, with Clopper-Pearson 95\\% intervals;",
        "$\\kappa$ is Cohen's kappa between raters on the TP/FP decisions.}",
        "\\label{tab:precision2}",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{@{}lrrlrlrr@{}}",
        "\\toprule",
        "Check & $n$ & \\multicolumn{2}{c}{Rater A} & \\multicolumn{2}{c}{Rater B} & Agree & $\\kappa$ \\\\",
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
        " & & TP & Prec. [CI] & TP & Prec. [CI] & & \\\\",
        "\\midrule",
    ]
    for _, r in t.iterrows():
        label = RULE_LABEL.get(r.rule, "\\textit{Pooled}")
        if r.rule == "pooled":
            lines.append("\\midrule")
        lines.append(
            f"{label} & {int(r.n)} & {int(r.tp_A)} & {100*r.prec_A:.1f} {r.ci_A} & "
            f"{int(r.tp_B)} & {100*r.prec_B:.1f} {r.ci_B} & {100*r.agreement:.0f}\\% & {r.kappa:.2f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (args.out_dir / "precision_audit_v2.tex").write_text("\n".join(lines))
    pd.set_option("display.width", 200)
    print(t.to_string(index=False))


if __name__ == "__main__":
    main()
