#!/usr/bin/env python3
# Copyright 2026 Yunus Emre Cogurcu - Apache-2.0
"""Repetition-to-repetition reproducibility under temperature-zero decoding.

The manuscript takes the model-task cell as the independent unit because
temperature-zero decoding makes the three repetitions "nearly identical".
This script measures how identical they actually are, at four levels, for
every cell of the baseline experiment (E1):

  text      the generated output files are byte-identical (md5)
  status    validity-gate status agrees (success / invalid_pseudocode / ...)
  binary    the binary violation verdict agrees
  count     the total violation count agrees
  rules     the set of fired rules agrees

Reported per model and pooled, together with the within-cell standard
deviation of the violation count. Supports the cell-level analysis unit
and documents that greedy decoding on the serving stack is not
bit-reproducible.

Usage:
    python3 scripts/review/rep_reproducibility.py --e1 results/E1_full/e1_results.csv \
        --code-dir results/E1_full/code --out-dir paper/tables
"""
from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

import pandas as pd

MODEL_LABEL = {
    "qwen2.5-coder:32b": "Qwen 32B",
    "deepseek-coder-v2:16b": "DeepSeek 16B",
    "codellama:34b": "CodeLlama 34B",
}
FNAME = re.compile(r"^(T\d{3})_(.+?)_(baseline|safety)_rep(\d)(\.invalid)?\.urscript$")


def file_hashes(code_dir: Path) -> dict[tuple[str, str, str, int], str]:
    out = {}
    for f in code_dir.glob("*.urscript"):
        m = FNAME.match(f.name)
        if not m:
            continue
        task, model_fs, cond, rep, _ = m.groups()
        model = model_fs.replace("_", ":", 1) if ":" not in model_fs else model_fs
        # file names use '_' for ':' (qwen2.5-coder_32b -> qwen2.5-coder:32b)
        model = re.sub(r"_(\d+b)$", r":\1", model_fs)
        out[(model, task, cond, int(rep))] = hashlib.md5(f.read_bytes()).hexdigest()
    return out


def build(e1: pd.DataFrame, hashes: dict) -> pd.DataFrame:
    e1 = e1.copy()
    e1["binary"] = (e1["total_violations"] > 0).astype(int)
    e1["rules"] = e1["violation_types"].fillna("").astype(str)
    e1["text_hash"] = [
        hashes.get((m, t, c, int(r)), f"missing-{m}-{t}-{c}-{r}")
        for m, t, c, r in zip(e1["model"], e1["task_id"], e1["condition"], e1["rep"])
    ]
    rows = []
    for (model, cond, task), g in e1.groupby(["model", "condition", "task_id"]):
        rows.append({
            "model": model, "condition": cond, "task_id": task, "n_reps": len(g),
            "text_identical": int(g["text_hash"].nunique() == 1 and not g["text_hash"].iloc[0].startswith("missing")),
            "status_identical": int(g["status"].nunique() == 1),
            "binary_identical": int(g["binary"].nunique() == 1),
            "count_identical": int(g["total_violations"].nunique() == 1),
            "rules_identical": int(g["rules"].nunique() == 1),
            "count_sd": g["total_violations"].std(ddof=0),
            "count_range": g["total_violations"].max() - g["total_violations"].min(),
        })
    return pd.DataFrame(rows)


def summarise(cells: pd.DataFrame) -> pd.DataFrame:
    keys = ["text_identical", "status_identical", "binary_identical", "count_identical", "rules_identical"]
    rows = []
    for cond in ["baseline", "safety"]:
        for model in list(MODEL_LABEL) + ["pooled"]:
            g = cells[cells.condition == cond]
            if model != "pooled":
                g = g[g.model == model]
            rec = {"condition": cond, "model": model, "cells": len(g)}
            for k in keys:
                rec[k] = int(g[k].sum())
            rec["count_sd_mean"] = g["count_sd"].mean()
            rec["count_range_mean"] = g["count_range"].mean()
            rows.append(rec)
    return pd.DataFrame(rows)


def to_latex(s: pd.DataFrame) -> str:
    lines = [
        "% Generated by scripts/review/rep_reproducibility.py -- do not edit by hand",
        "\\begin{table}[t]",
        "\\caption{Agreement between the three repetitions of each model-task cell in the",
        "baseline experiment under temperature-zero decoding. Cells in which all three",
        "repetitions agree at each level: byte-identical output text, validity-gate status,",
        "binary violation verdict, violation count, and set of fired rules; SD is the mean",
        "within-cell standard deviation of the violation count. Fifteen cells per model and",
        "condition. Safety is the safety-prompted condition.}",
        "\\label{tab:reps}",
        "\\centering",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{2.5pt}",
        "\\begin{tabular}{@{}llrrrrrr@{}}",
        "\\toprule",
        "Condition & Model & Text & Status & Binary & Count & Rules & SD \\\\",
        "\\midrule",
    ]
    prev = None
    for _, r in s.iterrows():
        if prev is not None and r.condition != prev:
            lines.append("\\addlinespace")
        prev = r.condition
        cond = "Baseline" if r.condition == "baseline" else "Safety"
        model = MODEL_LABEL.get(r.model, "\\textit{Pooled}")
        lines.append(
            f"{cond} & {model} & {int(r.text_identical)}/{int(r.cells)} & {int(r.status_identical)}/{int(r.cells)} & "
            f"{int(r.binary_identical)}/{int(r.cells)} & {int(r.count_identical)}/{int(r.cells)} & "
            f"{int(r.rules_identical)}/{int(r.cells)} & {r.count_sd_mean:.2f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--e1", type=Path, default=Path("results/E1_full/e1_results.csv"))
    ap.add_argument("--code-dir", type=Path, default=Path("results/E1_full/code"))
    ap.add_argument("--out-dir", type=Path, default=Path("paper/tables"))
    args = ap.parse_args()

    e1 = pd.read_csv(args.e1)
    cells = build(e1, file_hashes(args.code_dir))
    s = summarise(cells)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    cells.to_csv(args.out_dir / "rep_reproducibility_cells.csv", index=False)
    s.to_csv(args.out_dir / "rep_reproducibility.csv", index=False)
    (args.out_dir / "rep_reproducibility.tex").write_text(to_latex(s))
    pd.set_option("display.width", 200)
    print(s.to_string(index=False))
    print(f"Wrote {args.out_dir}/rep_reproducibility{{.csv,.tex,_cells.csv}}")


if __name__ == "__main__":
    main()
