#!/usr/bin/env python3
# Copyright 2026 Yunus Emre Cogurcu - Apache-2.0
"""Task table for the manuscript (revision item R2-6a).

Lists the fifteen baseline tasks with category, operating mode, tool, payload,
TCP speed cap, motion-command counts and the outcome-blind complexity tertile
from results/task_complexity_scores.csv (TASK_COMPLEXITY_SPEC.md).

Usage:
    python3 scripts/review/task_table.py --out-dir paper/tables
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

MOVE_TYPES = {"move_joint", "move_linear", "move_circular", "move_process"}
MODE_LABEL = {"collaborative": "Collab.", "fenced": "Fenced", "hybrid": "Hybrid"}
CAT_LABEL = {
    "pick_place": "Pick-place",
    "welding": "Welding",
    "palletizing": "Palletising",
    "inspection": "Inspection",
    "assembly": "Assembly",
    "material_handling": "Material handling",
    "processing": "Processing",
    "custom": "Custom",
}
TERTILE_LABEL = {"T_low": "Low", "T_med": "Medium", "T_high": "High"}


def load_tasks(tasks_dir: Path) -> pd.DataFrame:
    rows = []
    for f in sorted(tasks_dir.glob("T*.json")):
        t = json.loads(f.read_text())
        meta = t.get("task", {})
        seq = t.get("motion_sequence", [])
        tool = t.get("tool", {}) or {}
        safety = t.get("safety_requirements", {}) or {}
        rows.append({
            "task_id": meta.get("id"),
            "name": meta.get("name"),
            "category": meta.get("category"),
            "operating_mode": meta.get("operating_mode"),
            "tool_type": tool.get("type"),
            "payload_kg": (t.get("robot", {}) or {}).get("payload_kg"),
            "max_tcp_speed_mm_s": safety.get("max_tcp_speed_mm_s"),
            "human_proximity": bool(safety.get("human_proximity", False)),
            "n_commands": len(seq),
            "n_moves": sum(1 for c in seq if c.get("type") in MOVE_TYPES),
            "n_linear": sum(1 for c in seq if c.get("type") == "move_linear"),
            "n_joint": sum(1 for c in seq if c.get("type") == "move_joint"),
            "n_tool_ops": sum(1 for c in seq if c.get("type") in {"set_tool", "set_digital_output"}),
        })
    return pd.DataFrame(rows)


def to_latex(t: pd.DataFrame) -> str:
    lines = [
        "% Generated by scripts/review/task_table.py -- do not edit by hand",
        "\\begin{table*}[t]",
        "\\caption{The fifteen baseline tasks. Mode is the operating mode that sets the ceiling on the TCP",
        "speed; cap is the task's own speed limit at or below that ceiling; commands is the length of the motion sequence and moves the number of",
        "joint-space plus Cartesian motion commands within it; complexity is the outcome-blind",
        "tertile of the task complexity score (\\ref{sec:complexity}). All tasks include an",
        "e-stop verification step and a home pose; payload is the declared tool payload.}",
        "\\label{tab:tasks}",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{2.5pt}",
        "\\begin{tabular}{@{}llllrrrrrl@{}}",
        "\\toprule",
        "ID & Task & Category & Mode & Tool & Payload (kg) & Cap (mm/s) & Cmds & Moves & Complexity \\\\",
        "\\midrule",
    ]
    for _, r in t.iterrows():
        # the style contract of the manuscript bans em-dashes: "Linear weld path, fenced mode"
        name = str(r["name"]).replace(" \u2014 ", ", ").replace("&", "\\&")
        lines.append(
            f"{r.task_id} & {name} & {CAT_LABEL.get(r.category, r.category)} & "
            f"{MODE_LABEL.get(r.operating_mode, r.operating_mode)} & {r.tool_type} & "
            f"{r.payload_kg:g} & {r.max_tcp_speed_mm_s:g} & {int(r.n_commands)} & {int(r.n_moves)} & "
            f"{TERTILE_LABEL.get(r.tertile, r.tertile)} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--tasks-dir", type=Path, default=Path("paper/data/tasks_as_run"),
                    help="task IR as used in the experiments (snapshot), not the live directory")
    ap.add_argument("--complexity", type=Path, default=Path("results/task_complexity_scores.csv"))
    ap.add_argument("--out-dir", type=Path, default=Path("paper/tables"))
    args = ap.parse_args()

    tasks = load_tasks(args.tasks_dir)
    if args.complexity.is_file():
        cx = pd.read_csv(args.complexity)[["task_id", "tcs_total", "tertile"]]
        tasks = tasks.merge(cx, on="task_id", how="left")
    else:
        tasks["tcs_total"] = float("nan")
        tasks["tertile"] = "n/a"

    args.out_dir.mkdir(parents=True, exist_ok=True)
    tasks.to_csv(args.out_dir / "task_table.csv", index=False)
    (args.out_dir / "task_table.tex").write_text(to_latex(tasks))
    print(tasks[["task_id", "category", "operating_mode", "tool_type", "n_commands", "n_moves", "tertile"]].to_string(index=False))
    print("mode counts:", tasks.operating_mode.value_counts().to_dict())
    print("category counts:", tasks.category.value_counts().to_dict())
    print(f"Wrote {args.out_dir}/task_table.{{csv,tex}}")


if __name__ == "__main__":
    main()
